services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "80:8000"
    depends_on:
      - mariadb
    env_file:
      - .env
    command: ["fastapi", "dev", "src/main.py"]
    volumes:
      - ./src:/app/src
      - .env:/app/.env
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
