{
 "title": "Infrastructure Detail",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nginx Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nginx_connections_active)" }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(redis_memory_used_bytes)" }
   ]
  },
  {
   "title": "Nginx Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Redis Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentwide" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_keyspace_hits_total[1m])) / (sum(rate(redis_keyspace_hits_total[1m])) + sum(rate(redis_keyspace_misses_total[1m]))) * 100"
    }
   ]
  }
 ]
}