"""add profile fields

Revision ID: 6334792a92af
Revises: 22a3687f7498
Create Date: 2026-05-07 17:12:37.389837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6334792a92af'
down_revision: Union[str, Sequence[str], None] = '22a3687f7498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('users', sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
