"""add_actor_id_to_audit_logs

Revision ID: b1d0deaac444
Revises: 6334792a92af
Create Date: 2026-05-08 06:23:01.517539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1d0deaac444'
down_revision: Union[str, Sequence[str], None] = '6334792a92af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_audit_logs', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'movie_audit_logs', 'users', ['actor_id'], ['id'])
    op.add_column('user_audit_logs', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_audit_logs', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_audit_logs', type_='foreignkey')
    op.drop_column('user_audit_logs', 'actor_id')
    op.drop_constraint(None, 'movie_audit_logs', type_='foreignkey')
    op.drop_column('movie_audit_logs', 'actor_id')
    # ### end Alembic commands ###
