"""Fix cascade delete in movie audit logs

Revision ID: e61a4b83ac85
Revises: eab109fe4322
Create Date: 2026-05-05 05:34:31.463548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e61a4b83ac85'
down_revision: Union[str, Sequence[str], None] = 'eab109fe4322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_audit_logs_movie_id_fkey', 'movie_audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'movie_audit_logs', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_audit_logs', type_='foreignkey')
    op.create_foreign_key('movie_audit_logs_movie_id_fkey', 'movie_audit_logs', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
